checks:
  php: true

build:
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=psfs-coverage'
        coverage:
          file: 'psfs-coverage'
          format: 'clover'
  environment:
    php: '5.6.16'

filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/test/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*