checks:
  php: true

build:
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=psfs-coverage'
        coverage:
          file: 'psfs-coverage'
          format: 'clover'
  environment:
    php: '5.6.9'

filter:
  excluded_paths:
    - src/test/*
    - vendor/*
    - src/public/*
    - src/templates/*