checks:
  php: true

build:
  environment:
    php: "7.0"
    variables:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  services:
    mysql: "5.7"
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=psfs-coverage'
        coverage:
          file: 'psfs-coverage'
          format: 'clover'

filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/test/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*